name: Build and Publish RPM

on: [push]

jobs:
  build_rpm:
    runs-on: ubuntu-latest
    name: Build RPM
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build RPM
        id: build
        uses: Eljhoset/hello-build-action@build_publish
        with:
          rpm_output_folder: /rpm
