name: Build and Publish RPM

on: [push]

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Upload RPM
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: '100s'
          token_format: 'access_token'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Upload to Artifact Registry
        run: |
          gcloud config set artifacts/repository gcp-repo
          gcloud config set artifacts/location us-east1
          gcloud artifacts yum upload --source=$(ls *.rpm | grep -vE '(src|debug)')
